spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false
app.seed.enabled=false

app.payment.dev-mode=false
app.mail.enabled=true

logging.level.personal.ecommercebackend=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO

springdoc.show-actuator=false
